config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "dashboard#index"

  resources :histories
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/history.rb
class History < ApplicationRecord
  belongs_to :owner, class_name: 'Person'
  belongs_to :requester, class_name: 'Person'
  has_many :tasks

  enum allowed_statuses: [:pending, :started, :delivered, :accepted]

  validates :name, uniqueness: true
  validates :name, :requester_id, :status, presence: true
  validates :status, inclusion: { in: allowed_statuses.keys }
  validate :finished_at_cannot_be_previous_than_started_at, :points_in_range

  def self.valid_points
    [1,2,3,5,8,13]
  end

  def points_in_range
    if !History.valid_points.include? self.points
      errors.add(:points, "Somente são aceitos : 1,2,3,5,8,13")
    end
  end

  def finished_at_cannot_be_previous_than_started_at
    if started_at.present? && finished_at.present? && finished_at < started_at
      errors.add(:finished_at,  "A data de término nõa pode ser anterior à data de início")
    end
  end

  def next_status
    case status
    when "pending"
      "started"
    when "started"
      "delivered"
    when "delivered"
      if self.tasks.map(&:done).include? false
        "delivered"
      else
        "accepted"
      end
    else
      ""
    end
  end

  def previous_status
    case status
    when "started"
      "pending"
    when "delivered"
      "started"
    when "accepted"
      "delivered"
    else
      ""
    end
  end

end

app/models/person.rb
class Person < ApplicationRecord
  enum role: [:manager, :developer]

  validates :name, :email, presence: true
  validates :email, uniqueness: true
  validates :name, uniqueness: { scope: :role,
    message: "Já existe alguém com este nome com esta função" }
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :manager,  class_name: 'Person'

  validates :name, :manager_id, presence: true
  validates :name, uniqueness: true

  validate :manager,  if: :is_manager?

  def is_manager?
    if !Person.find(manager_id).manager?
      errors.add(:manager_id, ": precisa ser gerente para adicionar e  ser responsável por um projeto.")
    end
  end
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :history

  validates :description, :history_id, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end
end

app/controllers/histories_controller.rb
class HistoriesController < ApplicationController
  def new
    @history = History.new
    @people  = Person.order(:name)
  end

  def edit
    @history = history.find params[:id]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/histories_helper.rb
module HistoriesHelper
end

app/views/dashboard/index.html.haml
.row
  .col-md-1
  .col-md-10
    = link_to "new history", new_history_path()
%hr
.row
  - History.allowed_statuses.each do |status|
    .col-md-3.text-center
      = status[0]

app/views/histories/_form.html.haml
= simple_form_for @history do |f|
  .row
    .col-md-8
      = f.input :name
  .row
    .col-md-4
      = f.input :requester_id, collection: @people
    .col-md-4
      = f.input :owner_id, collection: @people
  .row
    .col-md-8
      = f.input :description, input_html: { rows: 6}
  .row
    .col-md-4
      = f.input :started_at, as: :string, input_html: { class: "datepicker"}
    .col-md-4
      = f.input :deadline
      .row
    .col-md-1
      = f.input :points, collection: History.valid_points
  %br
  .row
    .col-md-2
      = f.submit

app/views/histories/edit.html.erb
<h1>Histories#edit</h1>
<p>Find me in app/views/histories/edit.html.erb</p>

app/views/histories/new.html.haml
%h4 Nova história

= render partial: 'form'

= link_to 'voltar' , root_path()

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskBoard</title>
    <%= csrf_meta_tags %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <row>
      <h2 class="text-center">
        Task Board
      </h2>
    </row>
    <hr>
    <div class="container">
      <%= yield %>
    </div>

  </body>
  <!-- <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script> -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</html>